### ISSUE TITLE
There's a bug while trying to upload a video

### ISSUE THREAD

**Issue by Monredo** [TeamTracle/tracle#36]
When I tried to upload a video, it keeps getting a bug that this is not working as its 
status code 500 but then the request method "PUT" won't even respond.

Here's an example of a bug issue
> Request URL: https://tracle.tv/api/videos
> Request Method: PUT
> Status Code: 500 
> Remote Address: [2606:4700:3033::6815:555e]:443
> Referrer Policy: same-origin

**Comment by ajacobsen** [comment]
Are you using the uploader on the website?
It sounds like you might be trying to directly access the API endpoints.
