### ISSUE TITLE
Uploading of videos are temporarily disabled now

### ISSUE THREAD

**Issue by Monredo** [TeamTracle/tracle#39]
![Web capture_2-7-2023_133338_tracle tv](https://github.com/TeamTracle/tracle/assets/107286254/3c8d2ee1-70b3-4c55-a308-3d1eff448634)

Why does it show "**Uploading of videos has been temporarily disabled**"? Does that mean we won't able to upload videos in Tracle?

**Comment by Gabre-Rod** [comment]
It will stay like that for around a week.

**Comment by Monredo** [comment]
> It will stay like that for around a week.

Why?
