### ISSUE TITLE
Cant make a account

### ISSUE THREAD

**Issue by Kajtek21** [TeamTracle/tracle#42]
i cant make an account! everytime i try to make one it says email is taken! also the chapta won't verify!

**Comment by ajacobsen** [comment]
Hi,
if it says that the email is already taken, that means someone created an account with that email already.
try resetting your password to use the account associated with that address.

**Comment by Kajtek21** [comment]
Hello. I am sorry cause i was thinking this was broken but then i got a
confirmation email to create the account, so yeah that's why it's said
"email was taken" and but the way nobody knows about this email.
Thanks for the information!


niedz., 16 lip 2023, 02:43 użytkownik Andy Jacobsen <
***@***.***> napisał:
